"""Hutch#: non-adaptive Frobenius norm estimation (arXiv 2609.28472)."""

from hutch_sharp.estimators import (
    alpha_hat,
    alpha_hat_from_A_omega,
    frobenius_fourth_from_sq,
    frobenius_sq,
    gaussian_sketch,
    hutch_flat,
    hutch_flat_explicit,
    hutch_flat_matrix,
    hutch_sharp,
    hutch_sharp_matrix,
    matvec_rmatvec_from_matrix,
    one_sided_hutchinson,
    one_sided_hutchinson_matrix,
    optimal_alpha,
    optimal_alpha_from_singular_values,
    schatten_4_fourth,
    symmetrized_hutchinson,
    symmetrized_hutchinson_matrix,
    variance_hutch_sharp,
    variance_weighted,
    weighted_from_products,
    weighted_hutch_sharp,
    weighted_hutch_sharp_matrix,
    weighted_hutch_sharp_sketch_alpha,
    weighted_hutch_sharp_sketch_alpha_matrix,
)

__all__ = [
    "alpha_hat",
    "alpha_hat_from_A_omega",
    "frobenius_fourth_from_sq",
    "frobenius_sq",
    "gaussian_sketch",
    "hutch_flat",
    "hutch_flat_explicit",
    "hutch_flat_matrix",
    "hutch_sharp",
    "hutch_sharp_matrix",
    "matvec_rmatvec_from_matrix",
    "one_sided_hutchinson",
    "one_sided_hutchinson_matrix",
    "optimal_alpha",
    "optimal_alpha_from_singular_values",
    "schatten_4_fourth",
    "symmetrized_hutchinson",
    "symmetrized_hutchinson_matrix",
    "variance_hutch_sharp",
    "variance_weighted",
    "weighted_from_products",
    "weighted_hutch_sharp",
    "weighted_hutch_sharp_matrix",
    "weighted_hutch_sharp_sketch_alpha",
    "weighted_hutch_sharp_sketch_alpha_matrix",
]
